# Copyright 2023-2026 DreamWorks Animation LLC
# SPDX-License-Identifier: Apache-2.0

# Build up a copyright year string, eg 2017-2022
string(TIMESTAMP currentYear "%Y")
set(startingYear 2022)

if (${currentYear} GREATER ${startingYear})
    set(copyrightYear ${startingYear}-${currentYear})
else()
    set(copyrightYear ${currentYear})
endif()

set(header "// Copyright ${copyrightYear} DreamWorks Animation LLC
// SPDX-License-Identifier: Apache-2.0

// THIS FILE AUTO-GENERATED BY MoonraySamplingDefinitions.cmake

#pragma once

")

function(writeSamplingDefinitionsHeader defs)
    set(contents ${header})
    foreach(def ${defs})
        string(PREPEND def "#define ")
        string(APPEND contents ${def} "\n")
    endforeach()

    # Normalize line endings for platform-independent comparison
    set(normalizedContents "${contents}")
    string(REPLACE "\r\n" "\n" normalizedContents "${normalizedContents}")
    string(REPLACE "\r" "\n" normalizedContents "${normalizedContents}")

    set(headerFile ${CMAKE_CURRENT_BINARY_DIR}/SamplingDefinitions.h)
    
    # Only write if content changed to avoid triggering rebuilds
    set(writeFile TRUE)
    if(EXISTS ${headerFile})
        file(READ ${headerFile} existingContents)

        # Normalize line endings for comparison
        set(existingContentsNormalized "${existingContents}")
        string(REPLACE "\r\n" "\n" existingContentsNormalized "${existingContentsNormalized}")
        string(REPLACE "\r" "\n" existingContentsNormalized "${existingContentsNormalized}")

        if(existingContentsNormalized STREQUAL normalizedContents)
            set(writeFile FALSE)
        endif()
    endif()
    
    if(writeFile)
        file(WRITE ${headerFile} ${normalizedContents})
        message("Generated SamplingDefinitions.h")
    else()
        message("SamplingDefinitions.h is up-to-date")
    endif()

    # install(FILES ${CMAKE_CURRENT_BINARY_DIR}/SamplingDefinitions.h
            # DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/moonray/rendering/pbr/sampler)
endfunction()
